[package]
name = "raytracing"
version = "0.1.0"
authors = ["Tomi Hukkalainen <tomi.hukkalainen@iki.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.2.0"
winit = "0.24"
winit_input_helper = "0.9"
